#!/bin/bash

#è č
#æ ć
# ž
# š
# Š
# Ž
#È Č

convertdir="$@"
echo "Will change directory and subdirectories: $convertdir"
read

convertdir="."

ToUTF () {
 iconv -f ISO-8859-15 -t UTF-8 $i -o "$1.tmp"
 sed -i -e 's/è/č/g' -e 's/æ/ć/g' -e 's//ž/g' -e 's//š/g' -e 's//Š/g' -e 's//Ž/g' -e 's/È/Č/g' "$1.tmp"
 mv "$1" "$1.original"
 mv "$1.tmp" "$1"
}

list="`find "$convertdir" -depth -iregex '^.*\(\.srt\|\.sub\)' -printf '%p|'`"
IFS='|'
for i in $list; do
  if [[ `file $i | grep -c "Non-ISO.* extended-ASCII.* text"` -gt 0 ]]; then
    ToUTF "$i"
    echo "Done $i"
  else
    echo "Skipped $i"
  fi
done
unset IFS
